global_frame: map
rolling_window: false
track_unknown_space: true

plugins:
  - {name: global_dynamic_map,              type: "costmap_2d::StaticLayer"}
  - {name: global_inflation,                type: "costmap_2d::InflationLayer"}