global_frame: map
rolling_window: false
track_unknown_space: true

plugins:
  - {name: static,                          type: "costmap_2d::StaticLayer"}
  - {name: static_inflation,                type: "costmap_2d::InflationLayer"}
#  - {name: static_obstacles,                type: "costmap_2d::ObstacleLayer"}