global_frame: odom
rolling_window: true

plugins:
  - {name: obstacles_laser,                     type: "costmap_2d::ObstacleLayer"}
  - {name: obstacles_inflation,                 type: "costmap_2d::InflationLayer"}