footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.5

robot_base_frame: base_link_uav0
update_frequency: 5.0
publish_frequency: 2.0
transform_tolerance: 0.5

resolution: 0.2

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions

obstacles:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 1.0
    resolution: 0.1