#goal definition
uint8 EXPLORATION_MODE=0
uint8 ESCORTING_MODE=1
uint8 HYBRID_MODE=2

uint8 mipp_mode
float64 max_time
---
#result definition
float64 time_used
int64 voxels_discovered
---
#feedback
float64 time_used
int64 voxels_discovered